### ISSUE TITLE
Create sikuli tests for spreadsheet next release

### ISSUE THREAD

**Issue by cesine** [OpenSourceFieldlinguistics/FieldDB#1780]
We are getting close to a release. @hisakonog  , first @farahabbasi  and I will work on making these tests in skiuli, then we will turn it over to you for human testing (it might be at least 2-3 more days before you can start). @hisakonog  if you think of anything else we need to test, please edit this list. 

 - [x] load the app (http://appdev.lingsync.org)
 - [x] login
 - [x] if browser (firefox) remembers password user can just click login
 - [x] register
 - [x] create a corpus
 - [x] rename a corpus
 - [x] edit a corpus description and view the changes in hovering over the corpus in the corpora list
 - [x] select corpus
 - [x] change to another corpus
 - [x] it should show the corpus title and current session on the black nav bar when editing data
 - [x] enter 1 datum
 - [x] delete 1 datum
 - [x] keyboard focus always goes first field in edit template (when you use teh arrows to go between datum)
 - [x] up and down arrows goes between datum and between pages once you are in a datum
 - [x] enter in a new datum brings you to the next datum, in a normal datum it does nothing
 - [ ] new datum are showing on the page you are on, until you use a pagination arrow,then they fall into the chronological order they were entered
 - [x] tab takes you between fields in the data
 - [x] hover over a field tells you the teams help conventions of that field
 - [x] optional grammatical judgement shows up in front of utterance
 - [ ] ~~refresh page and see if fields for McGill template show up (Utterance, Morphemes, Gloss, Translation, IPA, Notes)~~
 - [x] use full template
 - [x] load the app uses the fulltemplate regardless of the local storage preferences
 - [x] use full template with user specified fields
 - [ ] ~~use mcgill template (no longer needed, corpus admins can customize the interface themselves)~~
 - [ ] ~~use yale template (no longer needed, corpus admins can customize the interface themselves)~~
 - [ ] ~~use compact template (no longer needed, corpus admins can customize the interface themselves)~~
 - [ ] use pagination arrows
 - [x] save 1 or many datum
 - [x] edit 1 or many datum in the same version
 - [x] edit 1 or many datum from a previous version
 - [ ] editing a datum should produce only one activity and only one modified by users field
 - [x] create a new session
 - [x] app selects most recent session by default
 - [x] edit a session
 - [x] delete a session
 - [x] record audio 
 - [ ] ~~record video~~ 
 - [x] upload an mp3 
 - [x] upload a wav
 - [x] upload a mp4 (or any movie)
 - [x] add a comment
 - [x] search for something
 - [x] search for t 
 - [x] search for z 
 - [x] click on export
 - [x] the new fields (ipa and notes) are exported correctly
 - [x] export a lot of data
 - [x] enter wrong password
 - [x] enter wrong username
 - [x] reset password
 - [x] reset password (non matching passwords)
 - [x] try connecting to server when user is offline
 - [x] try connecting to server when server is offline
 - [x] test glosser
 - [ ] others...

**Comment by cesine** [comment]
You've deployed the new version to appdev, so I assume it is working on your end (it's the version LingSync v2.36.30.05.24ss yes?). But on my end the new version looks (and works) very very odd(ly). A few things I noticed so far : 

1) I can choose session in some corpora but in some others I can't. 
When I am in SpreadsheetTesting_Migmaq corpus (or YaleTemplateTesting corpus), I can choose a session and the app shows the data. When I am in Malayalam_field_methods corpus (or YaleTemplateTesting2 corpus) I can not choose a session; "Choose session" screen stays on and doesn't go anywhere. Although the Malayalam corpus was created through Prototype, other three corpora were created through Spreadsheet. nemo33 isn't an admin for SpreadsheetTesting_Migmaq but is an admin for other three corpora.  So I don't know what is going on...  


2) Strange URL
In SpreadsheetTesting_Migmaq and YaleTemplateTesting corpora where I am able to choose a session, the URL of the data entry screen is 
http://appdev.lingsync.org/#/spreadsheet/yalefieldmethodsspring2014template    
For both corpora. 
Am I supposed to reset the fields etc in the corpus setting before choo


3) Handlebars not working? 
The double curly brackets are showing up on the GUI. See the screenshot (I was in Migmaq corpus)


4) Save button not working when I am in SpreadsheetTesting_Migmaq corpus. 


5) And SpreadsheetTesting_Migmaq corpus shows data from Malayalam and YaleTemplateTesting too... See the screenshot. The data on top is Migmaq, but the one on the bottom is Japanese which is from YaleTemplateTesting corpus. (So it is good that the save button doesn't work, I certainly don't want Japanese in Migmaq corpus!) 


6) Since the save button doesn't work and I can not logout, I refreshed/reloaded the page. It shows "no data to display" and I get logged out. 


7) There is no hiding of the audio/video section? It no longer looks like "spreadsheet" and it actually is hard to see the data.

**Comment by cesine** [comment]
1) corpus admins can customize their corpus fields order and number of fields to show, so we dont have these templates anymore. we have to thinkabout how we want ot do the upgrade for these corpora, eitehr we modify their fields manualy (or we auto detect them and do it automaticaly, which i dont htink we have time for until those users' apps get upgraded too).

the good news is simple: the field methods have hteir own stabel verison of hte app , we wont upgrade the previous field methods courses until we are ready with this. 

2) we should fix this
3) i havent seen this with any of my testing corpora, i need the error message because the app is broken on your corpus)
4)i havent seen this with any of my testing corpora, i need the error message because the app is broken on your corpus)
5) i havent seen this with any of my testing corpora, i need the error message because the app is broken on your corpus)
6)i havent seen this with any of my testing corpora, i need the error message because the app is broken on your corpus)
7)i havent seen this with any of my testing corpora, i need the error message because the app is broken on your corpus)

**Comment by cesine** [comment]
@hisakonog my report

* fixed the $digest issue that lead to 3,4,5,6,7 #1798
* fixed the local prefs issue that lead to 2  #1800 #1801

**Comment by hisakonog** [comment]
2) URL no longer yalefieldmethods 
3) handlebars {{ }} not showing, I see normal data entry screen

Although I got the "pref needs to be updated" message, I still can't see the data. 
![screen shot 2015-01-04 at 10 18 12 am](https://cloud.githubusercontent.com/assets/760694/5606444/1aee5484-93fe-11e4-817d-15d9f3ca23dd.png) 

Modified the field in corpus settings, still can't see data. Clicked "save template" in UI settings and got this
![screen shot 2015-01-04 at 10 24 06 am](https://cloud.githubusercontent.com/assets/760694/5606455/980f874e-93fe-11e4-9770-c6747074dd43.png)

**Comment by hisakonog** [comment]
MOREOVER, I am losing my corpora every time I logout and re-login! This is the list of corpora for nemo33 
![screen shot 2015-01-04 at 10 45 31 am](https://cloud.githubusercontent.com/assets/760694/5606460/f6b1d040-93fe-11e4-8822-b34b2a31ff8c.png)

Used to have 20+ corpora but now the majority is gone including corpora I was testing (Malayalam, SpreadsheetTesting_Migmaq). Console, this one was repeated 15 times: 

![screen shot 2015-01-04 at 10 52 26 am](https://cloud.githubusercontent.com/assets/760694/5606502/f09a6734-93ff-11e4-920c-e193bbfbc774.png)

**Comment by cesine** [comment]
@hisako thanks for those errors, i think they are fixed now

today I finished tests for creating and deleting session sand creating and deleting datum and recording audio and uploading audio. my changes are deployed as 

LingSync v2.37.04.11.56ss Sun Jan 4 11:59:22 EST 2015


I turn testing over to you, go for it, i think its ready for thorough testing.

**Comment by hisakonog** [comment]
- [x] Click on export 

When not checking WordPress Gloss: 
![export](https://cloud.githubusercontent.com/assets/760694/5619851/d1242760-94f3-11e4-8a36-94b648943777.png)

When checking WordPress Gloss: 
![exportneedwpgloss](https://cloud.githubusercontent.com/assets/760694/5619854/d751926c-94f3-11e4-9a26-716761684930.png)

**Comment by hisakonog** [comment]
- [x] Rename a corpus 

Corpus renaming takes immediate effect in "Corpus-Name loaded" and in the title bar (next to the save button) but in the corpora list. In order for the name in the corpora list to change, users need to logout and re-login
![screen shot 2015-01-05 at 1 51 34 pm](https://cloud.githubusercontent.com/assets/760694/5623746/b1f6bce4-9526-11e4-9a76-8fbd13984868.png)

**Comment by cesine** [comment]
@hisakonog these above commits are deployed and ready for your testing. i think all of the things you found were addressed. ( you can also try the app in French to see what it looks like)

**Comment by hisakonog** [comment]
@cesine re. audio recording: (in addition to making the record/stop/upload buttons more obvious) the save button should turn to **red**. When uploading the recorded audio finishes, the audio plays automatically but I don't see the uploaded audio file yet. When I click "Saved" (i.e. it's green) the file shows up and I can play it. 

re. audio uploading: both drag-and-drop and "upload file" button work, but I need to click green "Saved" button to see and play the uploaded files. Also it would be nice if file names appear in the box whe you drag-and-drop them there. 

re. video uploading: the mp4 file uploads but it plays as an audio (i.e. don't see the image)  

re. image uploading: I've uploaded a png file, I don't see the image and the console gives this: 

![screen shot 2015-01-06 at 10 10 14 am](https://cloud.githubusercontent.com/assets/760694/5630563/f384436e-958c-11e4-9a4e-70ef818ba500.png)

And the link from the uploaded file leads to (as expected) 
```{
  "status": 404,
  "userFriendlyErrors": [
    "Not found"
  ]
}```

**Comment by hisakonog** [comment]
- [x] load the app uses the fulltemplate regardless of the local storage preferences 
YES!!!

**Comment by cesine** [comment]
`save button should turn to red. `
`I need to click green "Saved" button to see and play the uploaded files.`
i agree about both of these, I tried many times to get these to work but nothing i do makes it show up

`Also it would be nice if file names appear in the box when you drag-and-drop them there.`
* okay sounds like a good idea

re. image uploading: I've uploaded a png file, I don't see the image and the console gives this:
* sounds like a problem with something adding mp3 to it.. i will look

**Comment by hisakonog** [comment]
- [x] use full template with user specified fields ~~**In order for the changes in Corpus and UI settings to take effect, users need to refresh page**~~ 
No need to refresh page, the change takes effect when clicking "save (changes)"

**Comment by cesine** [comment]
@hisakonog how far are we from not deploying? can we push some of these features to the next release (like the video and images) whatever we can push to the next release, can you make as seperate issues and tell me if we can deploy the current version from appdev to app...

**Comment by cesine** [comment]
@hisakonog i will go to sleep now and maybe take a look at anything else we need to do when i wake up around 8pm your time

**Comment by hisakonog** [comment]
@cesine Regarding the above issues I think the app is ready to be deployed and we can make separate issues for the remaining quirks. But I am finding other funky stuff (maybe related to the issues that you just fixed?) I report them below so you can decide whether these are critical.

**Comment by hisakonog** [comment]
New field name does not show immediately in UI settings: 
Add new field (change name, change convention) > Save 
Change order of fields > Save 
Go to UI settings, the newly added field show up in the right order but the name is still newField_digits 

![screen shot 2015-01-06 at 12 26 11 pm](https://cloud.githubusercontent.com/assets/760694/5632873/49149a96-95a0-11e4-9163-59052d251c62.png)

When I directly go to Data Entry from here, the fields show up correctly. But if I refresh page, it leads to Data Entry screen that has no fields. 

![screen shot 2015-01-06 at 12 11 31 pm](https://cloud.githubusercontent.com/assets/760694/5632913/8247cd60-95a0-11e4-98e5-8b340f32b941.png)

And the UI settings doesn't show the fields either 

![screen shot 2015-01-06 at 12 11 46 pm](https://cloud.githubusercontent.com/assets/760694/5632928/a40fe806-95a0-11e4-967d-cad9356700ce.png) 

Logout > re-login solves this, and most users won't refresh page so this may not be a big issue, but I found it interesting...

**Comment by hisakonog** [comment]
In Malayalam corpus, the sessions used to have "28-06-2013 Malayalam words" and "27 (or 26?)-06-2013 Malayalam words" but now both are "24/06/2013 Malayalam words".

**Comment by hisakonog** [comment]
How do I delete a session?

**Comment by hisakonog** [comment]
Create new session while in the session mode (not the corpus choose session) 
You can click "+Create New Elicitation session" button and session info text box show up. "Date Elicited" box lacks the drop-down calendar, even though it's available when clicking Edit Session Info.

**Comment by hisakonog** [comment]
@cesine The last 4 are the funky issues, of which the 1st/2nd maybe interesting, 3rd/4th not so much. I think the app can be deployed if you figure out what is going on behind 1/2 or you think they are not a big deal.

**Comment by cesine** [comment]
from richard :
Every so often all the fields disappear except for the grammaticality judgement. Logging out and back in has fixed it but it has happened a couple times on different computers.

**Comment by cesine** [comment]
`sessions used to have "28-06-2013 Malayalam words" and "27 (or 26?)-06-2013 Malayalam words" but now both are "24/06/2013 Malayalam words".` 

sessions are now based on Date elicted + goal (maybe the same as before) i dont know about the malayalam corpus. i will look and see if there is an error for your session data.


`how do i delete a session`

you have to have no more datum in your session before you can delete it

` lacks the drop-down calendar`

i made it into a date

**Comment by hisakonog** [comment]
@cesine I still have the same problem as the 1st comment (app version: LingSync v2.37.06.09.39ss Tue Jan 6 09:43:36 EST 2015)  Maybe there are two separate issues 1) the label for a newly added field doesn't show up in UI settings (it remains as newField_digits); 2) refreshing page somehow causes the fields to not show up. 
Refreshing page without doing any editing (no change in Corpus/UI settings, no editing/adding data) gave me the data entry page with no fields, only comments and user activities. 
If you can't replicate the problem, would it be something to do with the local prefs/settings? Shall we meet 9-9:30am your time?

**Comment by hisakonog** [comment]
I just saw Richard's comment. Maybe he is refreshing page too?

**Comment by cesine** [comment]
@hisako i wasnt able to deploy before falling asleep so the latest version wasnt on appdev, it is on appdev now i can meet when you are ready :)

**Comment by cesine** [comment]
@jrwdunham  @hisakonog i still cant get the recording icons to show in the deploy.. im going out to eat be back later

**Comment by cesine** [comment]
spoke too soon, i downloaded the vendor.js and found the version of fielddb was and tha it migh tbe the package json, im pushing again and if the build doesnt fail,then the appdev might have icons.. i cant check it on my phone.

**Comment by hisakonog** [comment]
@cesine  v2.37.09.07.19ss Fri Jan 9 07:22:17 EST 2015  no icons and lost the square boxes...  :( 
![screen shot 2015-01-09 at 10 07 58 am](https://cloud.githubusercontent.com/assets/760694/5681562/9ba797ba-97e7-11e4-92c3-613b06177dd0.png)

**Comment by cesine** [comment]
hew update message

![screen shot 2015-01-09 at 10 49 16 pm](https://cloud.githubusercontent.com/assets/196199/5682337/cde06422-9851-11e4-8545-686d17e51f15.png)

**Comment by cesine** [comment]
and we have icons! the reason was because the fielddb common js library was also using the recordmp3js library, at version 3, not version 5... so we finally have icons on the buttons.


![screen shot 2015-01-09 at 10 51 16 pm](https://cloud.githubusercontent.com/assets/196199/5682380/2a3be746-9852-11e4-8316-23ae524b56eb.png)

there were roughly6-8 people who used the app during the LSA, not sure why or how, but they did...

**Comment by hisakonog** [comment]
Yes we have icons, but I seem no longer to be able to record sound. The buttons work, it seem to upload but there is no sound in the file. Also it says "file from import" instead of "Download Praat TextGrid" 
![screen shot 2015-01-09 at 11 13 57 am](https://cloud.githubusercontent.com/assets/760694/5682853/37c2f8f2-97f1-11e4-94e6-54cca96c2c67.png)

**Comment by hisakonog** [comment]
screenshot with console log
![screen shot 2015-01-09 at 11 23 27 am](https://cloud.githubusercontent.com/assets/760694/5683014/6baf8396-97f2-11e4-8e10-d0277b623e06.png)
![screen shot 2015-01-09 at 11 23 50 am](https://cloud.githubusercontent.com/assets/760694/5683018/7a082b78-97f2-11e4-9825-0855f0be0ded.png)

**Comment by cesine** [comment]
i had the same problem in canary, but since i had chrome open i tried it and it was fine, so i restarted canary, and it was fine too. my chrome often has problems with video and audio (ie hangouts no sound, so i restart canary) so im not sure if its specific to our app, or just a way that the sound permisssions are broken in chrome.

**Comment by cesine** [comment]
i think everything in the list is tested adn working. i found that the spreadshet app is still addign factorial and/or multiple activities per edit but this is very hard to clean up so lets ignore it since we are going to retire the spreadsheet app aventually enyway

![screen shot 2015-01-10 at 09 47 26 am](https://cloud.githubusercontent.com/assets/196199/5690222/edc01254-98ad-11e4-8bb5-aed3e8234d5a.png)

**Comment by hisakonog** [comment]
I closed and reopened Chrome and the recording, uploading, textGrid are working fine.
